CREATE SCHEMA IF NOT EXISTS YOUR_SCHEMA AUTHORIZATION YOUR_PROFILE;

CREATE TABLE IF NOT EXISTS YOUR_SCHEMA.news (
    news_id SERIAL PRIMARY KEY,
    title VARCHAR(255) NULL,
    publisher VARCHAR(255) NULL,
    description VARCHAR(255) NULL,
    url VARCHAR(255) NULL,
    publishedDate DATE NULL,
    insertedAt TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS YOUR_SCHEMA.onthisday (
    onthisday_id SERIAL PRIMARY KEY,
    year SMALLINT NULL,
    event VARCHAR(255) NULL,
    publishedDate DATE NULL,
    insertedAt TIMESTAMPTZ(0) DEFAULT CURRENT_TIMESTAMP
);