CREATE SCHEMA IF NOT EXISTS YOUR_SCHEMA AUTHORIZATION ...;

CREATE TABLE IF NOT EXISTS YOUR_SCHEMA.news (
    news_id SERIAL PRIMARY KEY,
    title VARCHAR(255) NULL,
    publisher VARCHAR(255) NULL,
    description VARCHAR(255) NULL,
    publishedDate DATE NULL,
    insertedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS YOUR_SCHEMA.onthisday (
    onthisday_id SERIAL PRIMARY KEY,
    year SMALLINT NULL,
    event VARCHAR(255) NULL,
    insertedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);